### ISSUE TITLE
Bibtex Export: no month information 

### ISSUE THREAD

**Issue by aschumilin** [mkucej/i-librarian#104]
The export function provides only the year and no information about the month. Some journals expect the month to be present in references.

**Comment by aschumilin** [comment]
Thanks for the quick fix. However, according to bibtex docs, the month should be a 3-letter abbreviation.

**Comment by mkucej** [comment]
The numbers will work in Biblatex. Have you tried?

**Comment by aschumilin** [comment]
Yes, works with biblatex. Thanks.
