### ISSUE TITLE
Multiple other URLs breaks item display

### ISSUE THREAD

**Issue by bit-chemist** [mkucej/i-librarian#105]
I have a local instance of I, Librarian and have encountered some item display errors after importing and curating the library. I believe the common issue amongst the items causing the display problem is that they all have multiple $other_urls.

The error message I encounter is:  
```
Fatal error: Uncaught Error: [] operator not supported for strings in /mnt/crypt/srv/ilibrarian/functions.php:1837 
Stack trace: 
#0 /mnt/crypt/srv/ilibrarian/display.php(424): show_search_results(Array, 'library', Array, Array, Array, Object(PDO)) 
#1 {main} thrown in /mnt/crypt/srv/ilibrarian/functions.php on line 1837
```
  
which points to this piece of code:  
```
            $urls = explode("|", $paper['url']);
            while (list($key, $url) = each($urls)) {
                if (strpos($url, 'pubmed.org') !== false || strpos($url, '/pubmed/') !== false) {
                    $pmid_url = str_replace('pubmed.org', 'ncbi.nlm.nih.gov/pubmed', $url);
                } elseif (strpos($url, 'pubmedcentral.nih.gov') !== false || strpos($url, '/pmc/') !== false) {
                    $pmcid_url = $url;
                } elseif (strpos($url, 'adsabs.harvard.edu') !== false) {
                    $nasaads_url = $url;
                } elseif (strpos($url, 'arxiv.org') !== false) {
                    $arxiv_url = $url;
                } elseif (strpos($url, 'jstor.org') !== false) {
                    $jstor_url = $url;
                } else {
                    $other_urls[] = $url;
                }
            }
        }
```  
  
The PHP version I'm using is:
```
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```  
  
![screen shot 2017-03-06 at 21 07 10](https://cloud.githubusercontent.com/assets/9684493/23640109/0fa8f5ec-02b1-11e7-80ac-36dc6a6a8199.png)

**Comment by bit-chemist** [comment]
I found this: 
  
http://stackoverflow.com/questions/5879675/problem-with-fatal-error-operator-not-supported-for-strings-in

and so I changed `$other_urls[] = $url;` to `$other_urls = $url;` and it works, now displaying the entries with multiple other urls.

**Comment by mkucej** [comment]
Hm. I am not getting this error. The string is automatically casted to array. Is it something they added in 7.1? I will fix it in the next version.

**Comment by mkucej** [comment]
OK, this throws fatal error in PHP 7.1:
```php
$foo = '';
$foo[] = 'bar';
var_dump($foo);
```
There could be a lot of code like this all over. :-(

**Comment by mkucej** [comment]
Fixed.
