### ISSUE TITLE
No Backup/Restore option in 4.8

### ISSUE THREAD

**Issue by ssokolen** [mkucej/i-librarian#107]
I can't seem to find the Backup/Restore option in my remotely hosted library running version 4.8, with a superuser account. In my locally hosted 4.3 version, it's prominently displayed under tools. Is this a bug or am I missing something?

**Comment by mkucej** [comment]
The hosted version has Backup/Restore disabled. If you want to download your hosted library, please contact our customer support. Thank you.

https://i-librarian.net/support.php
