### ISSUE TITLE
Bibtex key can not be changed after mass upload of pdf : Bug

### ISSUE THREAD

**Issue by kaktux** [mkucej/i-librarian#11]
In 3.4.1 there seems to be a bug:
When mass uploading pdfs afterwards the BibTex key can not be edited - the letters in the fields are greyed out. This does not appear when uploading one by one.

Especially when new listings are marked as unknown (with keys like unknown-000-idx) this makes no sense.

**Comment by mkucej** [comment]
If you don't provide your own Bibtex key, I, Librarian uses a default key, which you can see as a placeholder in Edit tab. If you want a different key, just type your own and Save.

**Comment by kaktux** [comment]
I have to agree to disagree - just tested once again.
I did try this several times - each time the same.

1.Add record 
2.Add multiple pdfs (also with add multiple items - import bibtex) - access through remote/vpn
3.selected some pdfs
4.import
5.A bibtexkey is provided automatically to the uploaded pdfy (like Author-Year-IDNo)- and can't be changed to a different through the edit tab afterwards. 
The font is shown in grey - and nothing can be typed or deleted in that field - while all other fields can be changed (and use black font).
I know the option to provide a bibtex key while adding a single record - but I don't see that during mass upload a bibtex key can chosen (would make no sense anyway).

Can anyone else reproduce ths using Ilibrarian 3.4.1 on Ubuntu 14.04 server?
