### ISSUE TITLE
Is it possible to improve the quality of the internal PDF viewer?

### ISSUE THREAD

**Issue by pedosb** [mkucej/i-librarian#113]
The rendering is showing low-quality images when compared to the browser PDF reader. But with the browser one, I cannot annotate the PDF. Is there any solution?

As an example, I am uploading two images, when rendered with I, Librarian PDF reader, and another with the browser's one.

Click the image to see it in the full size (I use a large monitor to read the papers).

![screen shot 2017-11-30 at 2 40 33 pm](https://user-images.githubusercontent.com/266610/33445739-92a7ce2e-d5dc-11e7-83ca-37fa8e055c0e.png)
![screen shot 2017-11-30 at 2 40 00 pm](https://user-images.githubusercontent.com/266610/33445740-92caf624-d5dc-11e7-8141-fedaaaed21cc.png)

**Comment by mkucej** [comment]
You can increase the JPEG quality here:

https://github.com/mkucej/i-librarian/blob/master/pdfclass.php#L232

Or you can use Ghostscript's PNG device instead.

**Comment by pedosb** [comment]
Thanks that makes it better.
