### ISSUE TITLE
DOI lookup broken for IEEE

### ISSUE THREAD

**Issue by aschumilin** [mkucej/i-librarian#114]
According to [https://developer.ieee.org/XML_Gateway](https://developer.ieee.org/XML_Gateway), IEEE has recently suspended the XML Gateway service. 
So, adding a record by DOI now ends with an error message if the IEEE option is checked -- even though the request is executed successfuly against e.g. CrossRef.

**Comment by mkucej** [comment]
Thank you for reporting this. Correct, IEEE discontinued their API. To avoid the error message, remove IEEE in Tools->Settings from a list of services that I,Librarian connects to.

**Comment by mkucej** [comment]
fixed in 4.9
