### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by jlpoolen** [mkucej/i-librarian#115]
I have php7.1 (Gentoo) installed and I unzipped the archive and staged it on my apache server.  I thought the PHP requirement was 5.4+, but I now see that is just specified PHP 5.4.

Is there a plan to support PHP 7?  Is it a major effort to migrate an application from PHP 5 to PHP7?

**Comment by mkucej** [comment]
I, Librarian works on PHP 7.1.
