### ISSUE TITLE
Bugs in the SSRF fix

### ISSUE THREAD

**Issue by xiaoyinl** [mkucej/i-librarian#123]
1. After the fix ac2ea239, it now extracts the `Location` header field, and uses its value as the new URL.
https://github.com/mkucej/i-librarian/blob/592184a5b438c50da9012bff4887c19af3c9301a/functions.php#L913-L918
But the code will fail when the Location is a [relative URL](https://en.wikipedia.org/wiki/HTTP_location#Relative_URL_example), e.g. http://www.example.com may send `Location: /index.html`. This can be fixed by first constructing full URL and then do the recursive call.

2. I suggest adding `169.254.0.0/24` range to `$is_inner_ipaddress`:
https://github.com/mkucej/i-librarian/blob/592184a5b438c50da9012bff4887c19af3c9301a/functions.php#L830-L834
It's IPv4 Link Local address. Also in AWS EC2, user can uses access metadata from http://169.254.169.254/latest/meta-data/. [1] So it's better to block this range from external access.

[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by mkucej** [comment]
Thank you.

2. I think the link local IPv4 is 169.254.0.0/16, right? So this should work:
```PHP
    $is_inner_ipaddress =
        ip2long('127.0.0.0')   >> 24 === $ip >> 24 or
        ip2long('10.0.0.0')    >> 24 === $ip >> 24 or
        ip2long('172.16.0.0')  >> 20 === $ip >> 20 or
        ip2long('169.254.0.0') >> 16 === $ip >> 16 or
        ip2long('192.168.0.0') >> 16 === $ip >> 16;
```

**Comment by xiaoyinl** [comment]
Yes, it should be /16 . Sorry for the typo.

**Comment by xiaoyinl** [comment]
@mkucej For the Location part, f931c868 will still fail if the Location is a [protocol relative URL](https://en.wikipedia.org/wiki/URL#prurl), e.g. `Location: //www.google.com/`. It should check if the scheme part is null too.

**Comment by mkucej** [comment]
Should be OK now. I appreciate your help.

**Comment by xiaoyinl** [comment]
No problem! It looks good now.
