### ISSUE TITLE
Italicised words are deleted from title and abstract during import

### ISSUE THREAD

**Issue by hansduo** [mkucej/i-librarian#125]
Here is an example that I just ran on the i,Librarian demo server: 
http://dx.doi.org/10.1038%2Fs41420-017-0005-6
After import the titles lacks the last two words and the abstract is also cleared of formatted (italicised) words. I have not spent too much time researching the exact conditions that need to be met for this to happen, but it happens both when fetching metadata via pubmed or crossref.

Here is another paper:
http://www.pnas.org/content/115/12/E2791
At least crossref-import (or update) manages to almost get the title correct. But both crossref and pubmed-import deliver the abstract minus the italicised words.

**Comment by mkucej** [comment]
Should work correctly in version 5.
