### ISSUE TITLE
Compatibility on high dpi devices?

### ISSUE THREAD

**Issue by wuuuuuud** [mkucej/i-librarian#126]
On high dpi devices with system magnification, the height and width assigned are  different from the actual  number of pixels used. For example, for my laptop equipping a 15.6 FHD screen, 125% system zoom level, the full  width of the screen showed in Chrome is 1920/1.25. So the pdf image is overly zoomed when the width of pdf-viewer-img is set to the actual size of the image. I tested all the zoom option in the shortcut and got same results.

**Comment by mkucej** [comment]
Thank you for reporting this.Version 5 will be a complete re-design. We'll keep an eye on this. Are you talking about a browser zoom setting, or an OS level zoom?

**Comment by wuuuuuud** [comment]
OS level. I tested at 100% browser-level zoom and 125% os-level zoom

**Comment by mkucej** [comment]
This will be fixed in 5.0.0.
