### ISSUE TITLE
GDPR on self-hosted instance. Suggestions?

### ISSUE THREAD

**Issue by devNull2013** [mkucej/i-librarian#128]
Hi Martin,
we're running a self-hosted instance of i-librarian (v 4.10). 
I'm wondering how i-librarian adresses the upcoming GDPR directives.
Are there any plans to add something like a "Privacy Policy" item on the welcome page or are we supposed to take care of this by ourselves?
What would you suggest?

Thank you very much.

**Comment by mkucej** [comment]
We have no immediate plans to deal with GDPR. We are a US-based company and do not specifically advertise to EU citizens.

**Comment by devNull2013** [comment]
OK, many thanks for your prompt reply.
