### ISSUE TITLE
Institutional authors

### ISSUE THREAD

**Issue by mkucej** [mkucej/i-librarian#129]
Improve handling of institutional authors:

http://timmurphy.org/2011/02/15/using-an-organisation-name-as-an-author-in-bibtex/

**Comment by EdGrrr** [comment]
Just to add to this. I have currently been putting institutional authors in the lastname field in i-librarian.

For simple cases, where there is a single "word" as the author (e.g. IMO, UN, AAPA), the export places an extra comma after the "author", which bibtex then doesn't like.

I think this could all be solved together. If there is no firstname in the i-librarian database, then could you assume that the name is an institution (or a person with no first name), in which case there should be no trailing comma and the word order should be protected?

A potential fix is to check for an empty firstname first. I have attached a PR (#147 )  that fixes this for bibtex, but I am not sure if there are issues with other export types.

**Comment by mkucej** [comment]
Thank you for your message. Yes, this will be solved in upcoming 5.0.0.

**Comment by EdGrrr** [comment]
Brilliant, thanks!
