### ISSUE TITLE
i18n available?

### ISSUE THREAD

**Issue by TomHummel** [mkucej/i-librarian#134]
Are there any plans for translating the user interface of i-librarian?

**Comment by mkucej** [comment]
It has been discussed, but it is on a low-priority list.

**Comment by Zugrik** [comment]
Is there any way to let community to do the translation in open-source way? Say, placing some file with names of all menus, tabs and text and let the people do the translation by themselves. I can do russian one if you let.

**Comment by mkucej** [comment]
i18n support was added in 5.6.0
