### ISSUE TITLE
Uncaught Error upon deletion of record

### ISSUE THREAD

**Issue by pintomollo** [mkucej/i-librarian#136]
The procedure was the following: Filter a list of records by selecting a category, go to the edit section of a record, delete this record. I then got the following error where the list of records use to be:

Fatal error: Uncaught Error: Call to a member function fetchAll() on boolean in /usr/share/i-librarian/www/items.php:87 Stack trace: #0 {main} thrown in /usr/share/i-librarian/www/items.php on line 87

**Comment by mkucej** [comment]
Will be fixed in 5.0.0.
