### ISSUE TITLE
PDF: highlight search url only use first word

### ISSUE THREAD

**Issue by nebrot** [mkucej/i-librarian#137]
https://github.com/mkucej/i-librarian/blob/07a2668ae012ff0d3fbede934fa526cd7d1c7c41/functions.php#L1906

Because of this line the parameter "&search_term=" only contains the first word for the URL of pdfviewer.php, but the URL should contain the whole term. Is there a reason for this? I think this should be:
`$pdf_search_term = $search_term;`

Example:
$search_term: testword1 testword2
$pdf_search_term: testword1 <---wrong, should be exactly like $search_term!

**Comment by mkucej** [comment]
I think the reason was that the PDF viewer search does not deal with multi-word phrase searches very well. But it could be improved. We will take a look at it for the next version.

**Comment by mkucej** [comment]
Fixed in version 5.
