### ISSUE TITLE
Improvements to 'Add Record UX'

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#14]
I have two suggestions for improving the user experience of editing the details of a new record:

* When a user adds a single item by specifying the URL of a PDF on the web, this URL should be automatically recorded in the URL field (unless it is over-written by data obtained using the doi).

* Since changing the 'publication type' field changes the displayed names of other fields, it should probably be repositioned to be more promiment and nearer the top of the list of fields

**Comment by mkucej** [comment]
Implemented.
