### ISSUE TITLE
Date conversion before 1970

### ISSUE THREAD

**Issue by EdGrrr** [mkucej/i-librarian#142]
Putting a publication date in the format YYYY-MM-DD where the year is before 1970 results in wrong date being shown on the 'item' page.

E.g. "1884-01-01" - Displays "(1970 Jan 1)"

Entering only the year results in the correct date being shown.

E.g. "1884" - Displays "(1884)"

**Comment by mkucej** [comment]
Improper use of `strtotime()`. Will be fixed in 5.0.0.
