### ISSUE TITLE
Make "Try OCR" button in "files" interface independent to presence of any text.

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#145]
Hello, Martin.

Discover this interesting issue: if pdf has some text, e.g. publisher notes or maintenance ones, not related to article itself, Librarian fetches this short text. If the article text is only available as scan layer, there is no option to try OCR to this pdf, as Librarian already thinks everything ok with text it fetched. Maybe it's worth to make "Try OCR" button always available and independent to presence of any fetched text? Thus we make user decide whether to rewrite text with OCR one or leave directly fetched one.

Best wishes,
Eugene.

**Comment by mkucej** [comment]
Hi Eugene:

Thank for your message. The OCR function will be available, whether there is a text or not in I, Librarian 5.0.0.
