### ISSUE TITLE
Spaces in custom BibTex fields can cause problems

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#15]
The defaut name of the custom fields ('Custom 1', 'Custom 2' etc.) contain spaces, which are included when records are exported to bibtex files.

This causes some tools (e.g. [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc)) to fail to parse the .bib file unless it is manually fixed.

A solution would be to export the custom fields with the spaces in their names replaced by a hyphen (e.g. 'Custom-1').

**Comment by mkucej** [comment]
Please, note that now you can rename custom fields in **Tools->Setings** to alleviate this bug.

**Comment by mkucej** [comment]
Fixed.
