### ISSUE TITLE
Adding option to pick temporary directory

### ISSUE THREAD

**Issue by Nicocys** [mkucej/i-librarian#16]
Is it possible to add an option to select a temporary directory ?
The installtion at the moment uses /var/tmp/ by default with Linux, which isn't suitable for me.
I managed to change it directly in data.php, but it would be better to have an option somewhere to change this.

Also, it would be nice to have a clear error message when the temporary directory isn't writable, as this leads to all sorts of failures, such as the content being imported but unaccessible, uneditable and undeletable. This also makes it impossible to import pdfs.
This is totally understandable, but there is no error message signalling that this is not normal behavior.

**Comment by mkucej** [comment]
I wonder why is /var/temp not working? I agree about the error message, if temp dir fails.

**Comment by Nicocys** [comment]
The not working part is probably due to me, though I even tried to create the folder manually and assign it all the rights (chmod 777).
In the end it was easier to just change it in data.php.

But the main issue is that lack of error message, as it took time to understand why I could add files/entries, and have them appear in the list in the library, but being completely unable to edit/open them (quick view shows the different fields as it should, but clicking on the title just led to an empty white page saying that no doc is found).

**Comment by mkucej** [comment]
It is possible you ran into the PrivateTmp mess in systemd. The so called security feature that breaks applications left and right. Sometimes I hate Linux.

**Comment by Nicocys** [comment]
Could be the reason, thanks for the link :)

**Comment by mkucej** [comment]
Temp dir is now checked in data.php and error will be displayed, if not writeable.
