### ISSUE TITLE
Adding an option to specify the LDAP field to use as login username

### ISSUE THREAD

**Issue by StreakyCobra** [mkucej/i-librarian#18]
Hi,

First let me thanks you for your nice application, I'm using it for more than two or three years now, and I'm really happy about it :grinning:

I'm using the LDAP authentication with success, but one detail annoys me: the common name being used as login. In my database the common name is the full name of the person, and as a posix account they have an `uid` field which is the username. Because of this, users have to use their real name (i.e. "John Doe") as login instead of their traditional username (i.e. `uid=` field, like "john.doe"), and it's different to all other services linked to the LDAP database. This is a big source of errors :wink:.

Did I miss a LDAP option that allows to specify the field to use as username? Otherwise it is hard to implement?
I'm ready to help if needed. I just looked at the code and I suppose [this](https://github.com/mkucej/i-librarian/blob/610821e8d4d07fc617e6f4d2e3d5e38adff241cc/index2.php#L312) is the part to edit, right?

**Comment by mkucej** [comment]
I am going to merge the code from @robodendron, it should allow you to change the `cn` to `uid` in ilibrian.ini: `ldap_username_attr`. I am not experienced with LDAP, sorry.

**Comment by StreakyCobra** [comment]
Thanks, I'll try it later :-)

**Comment by mkucej** [comment]
I am going to push my development branch later with the new LDAP code.

**Comment by StreakyCobra** [comment]
:+1:
