### ISSUE TITLE
In PDF viewer, the search results panel is not cleared after a search with no results

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#20]
In the PDF viewer, searching for a word contained in the PDF populates the 'search results' panel of the left.

If I then perform a search for a phrase that is not in the PDF, I receive a 'No hits' message, but the 'search results' panel is not cleared. It still contains the results from the previous search (and confusingly, clicking on a result no longer takes me to the corresponding position in the PDF).

**Comment by mkucej** [comment]
Fixed.
