### ISSUE TITLE
Journal name not correctly exported to BibTeX

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#21]
I have some papers with a 'Journal abbreviation', but no 'Secondary title'.

When I export these to RIS, the journal name is exported correctly (in the J2 field). However, when I export to BibTeX, no journal name is exported (there is no 'journal' field in the output). 

I think this is because of line 438 of export.php: this sets  $bibtex_translation['journal = '] to 'secondary_title', overriding its definition as  'journal' on line 432. Deleting this line seems to fix the problem.

**Comment by mkucej** [comment]
Those code lines are necessary to put journal abbreviation in the bibtex journal tag, if full journal name is empty. This code fixes the issue:
```
if ($item['reference_type'] == 'article'
    && !empty($add_item['journal'])
    && empty($add_item['secondary_title'])) {

    $add_item['secondary_title'] = $add_item['journal'];
}
```
Fix committed.
