### ISSUE TITLE
When importing metadata from Crossref, editor sometimes added as first author

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#22]
When importing metadata from Crossref, the editor is sometimes incorrectly added as the first author

An example for which this happens is doi:10.1371/journal.pcbi.1004457 - Costas D. Maranas is added to the author list. 

The function ``fetch_from_crossref($doi)`` in functions.php loads the url http://www.crossref.org/openurl/?id=doi:10.1371/journal.pcbi.1004457&noredirect=true&pid=i.librarian.software@gmail.com

However, it extracts the name of every contributor, rather than only those contributors whose contributor_role="author".

**Comment by mkucej** [comment]
Fixed.
