### ISSUE TITLE
Jabref Bibtex Import

### ISSUE THREAD

**Issue by einhander** [mkucej/i-librarian#23]
Hi,
I-librarian has complex problem on import bibtex from Jabref:
1. Import only work for bibtex key and first line of multiline title. No other information can be imported.
2. It imports title with {}, signs.
3. I have many custom fields in my bibtex file, more than 5
4. I've changed pdf file path relative to my server, but PDF not imported.

**Comment by einhander** [comment]
My bibtex file
[my-export.bib.txt](https://github.com/mkucej/i-librarian/files/34642/my-export.bib.txt)

**Comment by mkucej** [comment]
Thank you for reporting this. Your Bibtex files will work, if you change the tag names to lower case, e.g. Author->author. Unfortunately, this is yet another out of dozens of bibtex variations. A format without any united documentation. I will try to change the import routine to account for that, but RIS format might work better for you.

**Comment by einhander** [comment]
Thank you! I use Latex and Jabref as main instrumens. So use RIS format for bibliography isn't an option.

**Comment by mkucej** [comment]
Implemented.
