### ISSUE TITLE
Stall when accessing Windows I, Librarian installation from Internet Explorer 11 using hostname

### ISSUE THREAD

**Issue by thuehlinger** [mkucej/i-librarian#24]
I can access my local I, Librarian test installation (Windows 7, 64bit) using http://127.0.0.1:8080/librarian/ or the IP address http://10.x.x.x:8080/librarian/. However, if I use my hostname (which resolves to the same IP, i.e. 10.x.x.x.), the website gets stuck at the "load screen" (blue background, spinning wheel next to "I, Librarian" test). In other browsers (Firefox, Chrome) this does not happen, i.e. everything works fine).

**Comment by mkucej** [comment]
This is most likely caused by your IE11 settings like Compatibility View, or Security Settings that block Javascript. You can open IE11 Developer Tools with F12 to see which one is true.

**Comment by tbugfinder** [comment]
Enable Apache mod_headers in httpd.conf and add IE=EDGE header.
Maybe this could be added as a default setting to the windows package.

httpd.conf
LoadModule headers_module modules/mod_headers.so

ilibrarian.conf (in section <Directory "C:\ILibrarian">)
Header set X-UA-Compatible "IE=EDGE"

**Comment by thuehlinger** [comment]
These two changes seem to do the job. Thank you!

**Comment by mkucej** [comment]
While this solution may work, I don't recommend it. First, the X-UA-Compatible header is deprecated by Microsoft. The X-UA-Compatible header serves for incompatible apps to force the Compatibility view in IE. I, Librarian is compatible with >IE 9. Instead, you should change your settings in IE 11 to remove Compatibility View for Intranet websites. It is also possible that your domain name is in a list of web sites forced to be displayed in Compatiblity View. Hope this will help.

**Comment by tbugfinder** [comment]
X-UA-Compatible is deprecated with Windows 10 / IE11. If IE9 is used for I, Librarian in compatibility mode, setting the flag resolves the loading issue. Sometimes companies have setup compatibility mode which does not make sense any longer but which have to be dealt with.
Also the X-UA-Compatible flag could be used to downgrade to an earlier IE mode.
IMHO, deprecated does not mean - don't use it.

**Comment by mkucej** [comment]
Sure, if it works for you, use it. IE compatibility view is a mess and I wanted to list here a simpler solution, in case other users read this thread. To summarize, if *I, Librarian* does not work properly in IE9, 10, 11, or Edge, do the following:

1. Uncheck Display Intranet sites in Compatibility View in IE settings.
2. If (1) is not an option, add this meta tag to I, Librarian index.html to force the app out of the Compatibility View:
```html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
3. To force all apps on your server out of the Compatibility View add this to your Apache conf file:
```xml
<ifModule>
    Header set X-UA-Compatible "IE=EDGE"
</ifModule>
```

There are other reasons why the above may not work, like IE Enterprise Mode. Please contact Microsoft Support, if you have trouble with I, Librarian rendering correctly.
