### ISSUE TITLE
Dedicated workspaces for groups

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#27]
Is is possible to limit access to items for different groups of users or would you recommend adding a second directory (copy)+Apache configuration to a current installation?
Later option would mean Apache is serving two directories and I have to maintain users for both environments.

**Comment by mkucej** [comment]
While your workaround solution may work, it will be an additional hassle to maintain users at different libraries. It is not possible to restrict access to items to any users at the moment. Item ownership and restricted access can be implemented. While this is not a priority for the open source I, Librarian, we will be happy to implement this for you. Please contact as via e-mail to get a quote. Thank you.
