### ISSUE TITLE
Add Record hung - with manual upload of office file (W2K12)

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#28]
Hello,
today I had an issue with adding new records using the manual option and selecting a .docx file before saving first time.
There wasn't any error message, it was just sort of hung.

On the server side there were multiple soffice.bin processes running (working in a weired temp folder).

Is there an error handling in case soffice.bin is not returning?
How could I get more details why soffice.bin processes did not return?

I killed all soffice.bin process and was able to proceed.

Thanks

**Comment by mkucej** [comment]
Conversion of office files to PDFs is handled externally by LibreOffice. The running soffice.bin processes is LibreOffice trying and failing to convert your docx to pdf. I wonder whether you can convert the same docx file directly in LibreOffice? If not, try to upgrade LibreOffice to the newest version.
