### ISSUE TITLE
Allow multiple simultaneous sessions from same user

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#29]
I run i-librarian on a server, and it would be convenient for me to remain logged in on both my laptop and desktop.

However, this is currently not possible, since whenever a user logs in, any existing sessions are deleted from the database by the block of code under the comment "ALLOW ONLY ONE LOGIN AT A TIME" in `index2.php`.

Why is the rationale for this design?

**Comment by mkucej** [comment]
It is a business decision. We charge per user account, and we don't allow to sign in from more than one device. One session for desktop version, plus one session for mobile version. The code moved in I, Librarian 4.0 to` authenticate.php`. You can safely comment it out on your server. Feel free to check out the `develop` branch. It will be merged with master in upcoming days.

**Comment by jamesscottbrown** [comment]
Great. Thanks for the explanation.
