### ISSUE TITLE
Sorting by 'Date Added' broken

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#30]
Running the latest version of i-Librarian, sorting by 'Date Added' on the library page is broken: the top entries are papers I added on June 1014.

Debugging by adding a print statement to the `perform_search()` function in `functions.php`, I see that the query being executed is:

    SELECT id,file,authors,title,journal,secondary_title,year,volume,pages,abstract,uid,doi,url,addition_date,rating,bibtex FROM library WHERE id IN (SELECT itemID FROM history.`search_d827f0ca` ORDER BY id DESC LIMIT 5 OFFSET 0) ORDER BY id DESC 

Using sqlite3 at the commandline to run 
    
    SELECT id,file,authors,title,journal,secondary_title,year,volume,pages,abstract,uid,doi,url,addition_date,rating,bibtex FROM library ORDER BY id DESC LIMIT 5
shows the top 5 papers I would expect.

It therefore looks like the cache table is breaking something.

**Comment by mkucej** [comment]
Hmm. The query looks good. This might be a tricky one. Thank you for reporting it.

**Comment by mkucej** [comment]
I don't see the same problem with my databases. It leads me to believe the bug is because SQLite does not guarantee ordering by id if not explicitly stated. Is the ordering bug in your database specific to `Date added` only?

**Comment by jamesscottbrown** [comment]
Ordering by `Title` or `Date Published` looks correct. 

I can't tell if ordering by `Rating` works, as I haven't rated any papers.

Ordering by `Journal` looks wrong: I have papers from Genome Research, EMBO Reports, Proceedings of the National Academy of Sciences, and Cell Biology Education appearing in that order. However, this is the same ordering as given by I, Librarian 3.5, so is a different issue.

**Comment by mkucej** [comment]
Thank you. I can't really test this, because my db is ordered correctly. I suspect that pages in your db got rearranged at some point. Anyway, could you try to comment out lines 181, 182 in display.php to see if it helps:

https://github.com/mkucej/i-librarian/blob/master/display.php#L181

**Comment by mkucej** [comment]
> Ordering by Journal looks wrong

This is because the ordering is by `journal` field, which I suspect is empty in those records that are displayed first.

**Comment by jamesscottbrown** [comment]
This is because the ordering is by journal field, which I suspect is empty in those records that are displayed first.

You are correct - the papers that appeared out-of-order had the journal name recorded in the `secondary_title` (rather than `journal`) field.

    Anyway, could you try to comment out lines 181, 182 in display.php to see if it helps:

This doesn't help: although these lines clear `$ordering`, `$orderby` is still equal to `'id'`, so the if loop on line 139 of functions.php still adds the `ORDER BY id` to the SQL query: https://github.com/mkucej/i-librarian/blob/master/functions.php#139

**Comment by mkucej** [comment]
> This doesn't help.

The items are probably pulled from the cache table. Please clear the cache by, e.g. adding or removing an item from Shelf.

**Comment by mkucej** [comment]
Will be fixed in 4.1
