### ISSUE TITLE
Unable to follow links in PDF?

### ISSUE THREAD

**Issue by sabian2008** [mkucej/i-librarian#36]
Hey, thanks for this great OSS tool. It's a great amount of time and effort in this project and I sincerely hope it's paying off for you, because it's certainly some good piece of software.

I've googled around and found nothing. Today I tried reading my first pdf document in i-librarian and, although I was surprised of how well it managed annotations, I found it strange I couldn't follow the links inside the pdf (to it's own equations). Text is formatted as link, but impossible to use.

If this is a known bug (which I guess it is) let this report RIP. Otherwise, if solicited, I could upload the PDF.

Thanks for everything!

**Comment by mkucej** [comment]
If you mean PDF Link annotations, those are not implemented. We will look into that. Thanks for taking time to report this.

**Comment by sabian2008** [comment]
I mean links like the ones in blue, which point to another part of the document itself (but are not in a TOC so to appear in bookmarks):
http://i.imgur.com/IKpdhaH.png

If feature is going to be implemented, although you've probably thought about it already, it's a nice feature some navigation between them. A couple of forward and back buttons which let's you see a reference and quickly come back to the piece of text you were reading.

**Comment by mkucej** [comment]
Done.

**Comment by sabian2008** [comment]
Great news. I've search the commits, It seems to me that de "Back" fuction is implemented with shortcut "r", right?

I'll be looking forward to the v4.2 .deb.

Thanks you a lot for this awesome FOSS. I look forward to contributing in the future.

**Comment by sabian2008** [comment]
Tried the PDF viewer improvements. It's getting much better really fast. Awesome development. Some point in the future, it would be perfect to go to the exact location, not just the page. I'll try to read how other viewers implement it. The back function works as expected, same as hiding controls with C.

Can't thank you enough. With this feature, reading is much more dynamic. 

All I can do right know is spread the word to fellow students and professors. I'd like to contribute to the project in the near future.

**Comment by mkucej** [comment]
I, Librarian extracts links using Poppler's pdftohtml, which does not provide any information about the exact location of the link targets, only a page number.
