### ISSUE TITLE
Required binary executables not working

### ISSUE THREAD

**Issue by user9011** [mkucej/i-librarian#48]
Hey, i have a problem with Required binary executables.

Pdftotext	PDF full-text search	not working	!!!
Pdfinfo	built-in PDF viewer	not working	!!!
Pdftohtml	PDF search in the built-in PDF viewer	not working	!!!
Ghostscript	icon views, built-in PDF viewer	not working	!!!
Pdfdetach	unpacking PDF-attached files	not working	!!!

OS: Windows Server 2008 R2.

Have you a idea?

Thanks.

**Comment by mkucej** [comment]
Do you have the binary files in bin subfolder? If yes, it could be some permission issue. Try to install I, Librarian to a folder with more relaxed permissions.

**Comment by mkucej** [comment]
See for a fix here:
https://github.com/mkucej/i-librarian/issues/64
