### ISSUE TITLE
SAVE button not active after adding record - by design ?

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#52]
Version 4.1

Steps:
- Stop librarianserver
- Cleanup Librarian TEMP folder
- Start librarianserver
- check that no soffice (LibreOffice4 is installed) processes are running

- Logon
- Add Record
- Manual Upload
- Choose a DOCX file to import
- Set title - "TEST RECORD"
- PRESS SAVE
- WAIT FOR ITEM has been recorded notification

Any other changes within add record cannot be saved as the SAVE button is not active.
Should the saved record be displayed at this point?

Now open the Library and edit recently added record, edit, save OK.

Now select "Add Record" : Still the previous add record is displayed.

**Comment by mkucej** [comment]
Saving items is asynchronous. You don't have to wait for one item to finish recording. You can click `Save` and immediately click on `Add single item` again to refresh the form and record another item. I will look what can be improved so that the process is more user-friendly.

**Comment by mkucej** [comment]
Fixed. The upload form will be switched to the first Add Record menu.
