### ISSUE TITLE
Error! No text found in this PDF

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#55]
Hello Martin,

After last major update I can't (quite often in fact) attach PDF file to item. When I "Add single Item" and point to PDF file it says that "PDF file haven't been recorded". If I add PDF manually via Edit > Files I got "Error! No text found in this PDF". I attached example of PDF file that doesn't work out. At glance this is ordinary PDF from journal site with text layer so everything should work well but it doesn't.

[1.4942032.pdf](https://github.com/mkucej/i-librarian/files/173633/1.4942032.pdf)

Best wishes,
Evgeny Govras.

**Comment by mkucej** [comment]
I am not getting these errors. The PDF is recorded successfully. But it is not searchable in the PDF viewer, because it contains some invalid characters. I will try to improve I, Librarian so that it removes these characters.

**Comment by mkucej** [comment]
Turns out this is a bug in Poppler pdftohtml package. Not sure if I can do anything about it. Leaving this bug report open for now.

**Comment by Zugrik** [comment]
If it's third party's bug maybe worth to make "Error! No text found in this PDF" non-critical error. Because of it I can't download any of such texts. Maybe transform it into warning (for now) that this text will be unsearchable in built-in viewer?

**Comment by mkucej** [comment]
OK, I made some changes that try to repair malformed PDFs. It is going to be added in 4.3.

**Comment by Zugrik** [comment]
Thanks a lot!

**Comment by Zugrik** [comment]
Hello, Martin.

Unfortunattely, this bug happens again (my version is 4.6). Please see attached pdf. It contains russian text - maybe this is a problem?

Thank you for your assistance.

[JETPL_9_16r.pdf](https://github.com/mkucej/i-librarian/files/675821/JETPL_9_16r.pdf)
