### ISSUE TITLE
Multiple PDF add record not working

### ISSUE THREAD

**Issue by JMPeryn** [mkucej/i-librarian#57]
Hello, Everyone.

I recently installed the 4.1 Version using the full installer (with Apache&Php) after having unstialled my precedent version (4.0 wihich was working nicely). I am now unable to "Add record" multiple pdf from localhost. The system just says "batch imports has finished" but nothing happened. While "Add single item works" it does not recognize the DOI of the pdf (there is actually a by default DOI number writen in the field). 

Looking at my instal Details I get several errors (all the rest is OK) : 

Required php.ini settings:
max_input_vars	recommended 10000	1000	!!!

Required binary executables:

Pdftotext	PDF full-text search	not working	!!!
Pdfinfo	built-in PDF viewer	not working	!!!
Pdftohtml	PDF search in the built-in PDF viewer	not working	!!!
Ghostscript	icon views, built-in PDF viewer	not working	!!!
Pdfdetach	unpacking PDF-attached files	not working	!!!

*Optional binary executables:

Tesseract OCR	optical character recognition	not working	!!!
LibreOffice	office documents import and conversion	not working	!!!

thanks for your inputs

JM

**Comment by mkucej** [comment]
This is a second time binaries not working were reported. Let me have a look at that. They are obviously necessary for most I, Librarian tasks.

**Comment by mkucej** [comment]
See https://github.com/mkucej/i-librarian/issues/64

**Comment by choldil** [comment]
Hello,

I have the same issue that JMPeryn reported, with exactly the same problem with the binaries when I
look at my installation details.
I have checked your answer in #64 but my installation is in a linux server and I don't have any white space in the folder. 
Did I miss something? Any suggestion?

Thank you in advance!

C

**Comment by mkucej** [comment]
fixed in 4.2
