### ISSUE TITLE
I coundn't login in when using microsoft edge browser 

### ISSUE THREAD

**Issue by cedarice** [mkucej/i-librarian#58]
The version of I-librarian was 4.1. I can login in using Chrome, Firefox, but failed when using Microsoft edge software. After entered the right username and password, and pressed "Sign in" button, it retain the login page.

**Comment by mkucej** [comment]
OK, let me fire up the Edge virtual machine.

**Comment by mkucej** [comment]
I tested MS Edge and login works correctly. You can check the Developer Console for hints on which Edge settings cause your issue.
