### ISSUE TITLE
Bug in recording changes to a note

### ISSUE THREAD

**Issue by jamesscottbrown** [mkucej/i-librarian#6]
Changes to a note can be apparently lost (whilst really being stored as duplicate rows in the database and ignored) if a user creates a new note and then saves different versions without reloading the editor.

## Example scenario:

Suppose I open a file with no attached notes, and click on Notes->Edit to open the pop-up MCE editor.

I write some text, and click save. This fires a POST request to notes.php.

Then I edit this text, and click save again. This fires another POST request to notes.php.

Both requests have the notes and file paramaters set correctly, but the notesID parameter is "". Thus ``isset($_POST['notesID'])`` in notes.php evaluates to true, and update_notes in functions.php is called twice. Since ``empty($notesID)`` evaluates as true both time, two INSERTs, but no DELETEs, are performed in the database.

Now I look at a different document, before going back to the notes pane for the first document: notes.php will return the first version of my note (since this has the lowest value of notesID), and it will appear that my subsequent changes have been lost.

## Potential fix:

One way to fix this would be to get rid of the notesID parameter from the POST request, and modifify the update_notes function so that it looks up the notesID parameter itself rather than trusting the value provided to it as an argument.

**Comment by mkucej** [comment]
Thank you fro your detailed bug report.

**Comment by mkucej** [comment]
A fix will appear in the next release.
