### ISSUE TITLE
Batch Import seems to fail on large folders

### ISSUE THREAD

**Issue by DetlevCM** [mkucej/i-librarian#60]
IT kindly installed i-librarian for me (on CentOS 6.7 - it is what is used "here").

So far so good, BUT if I try to import a large folder in one go (400 documents) it starts and then stops seemingly...
(Side note: The link to databases does not work due to our proxy - just in case that could be the issue.)

**Comment by mkucej** [comment]
Your admin can set proxy in I, Librarian settings.

**Comment by DetlevCM** [comment]
Thanks, we discovered this later as well. I would still class this as a bug - as it should work fine without too.
