### ISSUE TITLE
Change of filename while viewing pdf via browser plug-in

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#61]
Hello Martin,
With last major update somehow changed name of PDF file when I view PDF via browser plug-in. Earlier the filename was ID_number.pdf, but now it is always pdfcontroller.pdf. It doesn't seem to be the browser problem. Moreover, if I view PDF via built-in viewer and then choose to save it, filename be ID_number.pdf. This issue complicates a little management of downloaded PDF files if I want to give them to someone.

Best,
Eugene.

**Comment by mkucej** [comment]
But I, Librarian never supported renaming PDF files. It has always been 00012.pdf, etc...

**Comment by Zugrik** [comment]
If so, I should look for some changes in behavior of my browser. Sorry for bothering.

**Comment by mkucej** [comment]
No problem. What's your browser/plugin combo?

**Comment by Zugrik** [comment]
It's Chromium with built-in plugin Chromium PDF Viewer. It's quite awkward that it continues to name pdf files pdfcontroller.pdf even if I switch this plugin off.

**Comment by mkucej** [comment]
I can confirm that Chrome PDF viewer ignores PDF file names and always names the file `pdfcontroller`. Unfortunately, there is nothing I can do about it. It is something that Google decided to do with their software.

Previous I, Librarian provided direct access to PDF files. This is not possible in newer versions for increased security, hence the change you see.

**Comment by Zugrik** [comment]
Thank you for explanation. Well, hope I can cope with this. Or maybe switch to internal viewer some day. Unfortunately, now it's a bit weaker than external ones, e.g. Okular.
