### ISSUE TITLE
Problem with author names containing an apostrophe

### ISSUE THREAD

**Issue by hansduo** [mkucej/i-librarian#62]
I just noticed a problem with the first author in this paper PMID:27015309
I entered it into the demo site's library. The name is changed from Houri-Ze'evi to Houri-Ze&#03 and the firstname is removed after saving the entry.

**Comment by hansduo** [comment]
Happens only when using pubmed as the source. Crossref will do it fine.

**Comment by hansduo** [comment]
Reason is: Crossref uses a unicode symbol ( \u2019 ), Pubmed uses plain ascii.

**Comment by mkucej** [comment]
Fixed in 4.2.
