### ISSUE TITLE
Libreoffice is installed, but not working in I, Librarian

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian#67]
I am working on a Linux environment with Libre Office installed. When I look at the installation details I see that I, Librarian reports it as not working.

I am suspecting the binaries are not found or installed in a different location (RHEL 7). I looked at the code and it seems it only works for Windows (details.php, line 218). It would be nice if it can include Linux as well.

**Comment by mkucej** [comment]
With all due respect, it is only an assumption. If you can indeed fix this by adding full path to soffice binary, I will add this feature for Linux. Please look here:

https://github.com/mkucej/i-librarian/blob/master/functions.php#L749
