### ISSUE TITLE
Add Multiple PDF Upload - items/PDFs missing

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#68]
Hello,

there is an issue with Multiple PDF Item upload (version 4.1).

Steps:
1) Add Record -> Add Multiple PDFs ->  from any computer
tick PubMed/NASA/CrossRef
tick "If metadata not found" option

2) Select Files (in this case e.g. 11 PDFs)

3) Define NewCategory: TESTIMPORT

4) IMPORT
=>Import process starts and import of PDFs is displayed in upper right corner.

5) Check items in category TESTIMPORT - there are only 9 items listed, one additional (DOI not found - correct) is in subcategory !unknown.

6) Check items added today -> only 9 items are listed.
Missing article seems to be: http://dx.doi.org/10.1016/j.jaci.2015.04.049.
I could not see an error message during import.
I miss the 11th file and I'm wondering why there are only 9 items listed in todays addition list instead of 10.

Thanks,
thb

**Comment by tbugfinder** [comment]
I'v run into debugging and in my case some PDO executions should include error handling.

remoteuploader.php - line 301 ($stmt->execute();) fails.

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: library.affiliation' in C:\ILibrarian\remoteuploader.php:301
Stack trace:
#0 C:\ILibrarian\remoteuploader.php(301): PDOStatement->execute()
#1 {main}
  thrown in C:\ILibrarian\remoteuploader.php on line 301




$stmt:
INSERT INTO library (file, authors, affiliation, title, journal, year, addition_date, abstract, rating, uid, volume, issue,
                            pages, secondary_title, tertiary_title, editor,
                            url, reference_type, publisher, place_published, keywords, doi, authors_ascii, title_ascii, abstract_ascii, added_by)
                            VALUES ((SELECT IFNULL((SELECT SUBSTR('0000' || CAST(MAX(file)+1 AS TEXT) || '.pdf',-9,9) FROM library),'00001.pdf')), :authors, :affiliation,
                            :title, :journal, :year, :addition_date, :abstract, :rating, :uid, :volume, :issue, :pages, :secondary_title, :tertiary_title, :editor,
                            :url, :reference_type, :publisher, :place_published, :keywords, :doi, :authors_ascii, :title_ascii, :abstract_ascii, :added_by)

**Comment by mkucej** [comment]
Thank you for the detailed report. This bug will be fixed in 4.2.
