### ISSUE TITLE
Add Multiple PDF Upload - DOI requirement

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#69]
Hello,

to me it is not obvious why a DOI is required when running "Add Multiple PDFs" import.
Does it mean only if a DOI is present that PubMed also is queried?
Would a query e.g. to PubMed only be sufficient / possible for Multiple PDFs import ?

Thanks

thb

**Comment by mkucej** [comment]
A DOI is extracted from a PDF and used to query PubMed and other databases. If a paper does not contain DOI, no database is queried. Such paper can be uploaded into the !unknown category.
