### ISSUE TITLE
Batch rename authors

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#7]
Hello Martin,

Here are two features that I believe will be of use in Librarian.
1) ~~Wrote about it in forum, maybe you didn't noticed. So, I think it might be useful to rename custom1+ fields to something meaningful. For example, for me it's vital to know language of publication for correct BibTeX compilation. I assume it's hard to rename fields in the very library.sq3 file because of backward compatibility. Maybe, it's good to offer user to choose in settings menu how custom fields will be named/shown. And show these names only in web-interface and in export while in database they remain custom1+.~~

2) Maybe you should add batch rename interface for authors name, as you did for journals. Of course, it's not so vital as with journals name, but it's quite odd when you have author with one last name and 5 different initials. Interface with quick sorting by first letter will be also very handy as it is in left menu bar.

Hope, you find these suggestions meaningful.

Best wishes,
Eugene.

**Comment by mkucej** [comment]
Renaming custom fields will appear in the next release.

**Comment by pintomollo** [comment]
I agree, merging different spellings for the same author would be very useful! Push.

**Comment by mkucej** [comment]
Will be implemented in 5.0.0.
