### ISSUE TITLE
debug logging

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#70]
Hi,

to me it's difficult to dig into the code if there are issues.
Would it makes sense to add some sort of debug switch to the config file and also print more log output if it is enabled.

--thanks
thb

**Comment by tbugfinder** [comment]
Maybe xdebug.dll and config could be included into the Win Package.

**Comment by mkucej** [comment]
I, Librarian code is pretty old. There are some error reporting options in data.php:
https://github.com/mkucej/i-librarian/blob/master/data.php#L6

Unfortunately, Xdebug is not included in the downloadable PHP packages for Windows.

**Comment by tbugfinder** [comment]
Would you accept code changes which add debug output? If yes, could you provide your favorite method?

Xdebug could be added to the Windows installer.
