### ISSUE TITLE
Upgrading 4.1->4.3

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#71]
Hi,

which is the preferred method for upgrading the a FULL Windows installations from 4.1 to 4.3 after modifying httpd.conf (e.g. SSL configuration), php.ini (add ldap) and ilibrarian-default.ini (probably should be ilibrarian.ini).

Thanks.

**Comment by mkucej** [comment]
Easiest is to download the ZIP archive and overwrite.

**Comment by cedarice** [comment]
@mkucej Is the same solution for Linux user to upgrade 4.1 to 4.3?

**Comment by mkucej** [comment]
Yes, you can use tar.xz package to overwrite.
