### ISSUE TITLE
Author list prefaced by collaboration name (particularly in arXiv)

### ISSUE THREAD

**Issue by christophra** [mkucej/i-librarian#73]
Often, the authors listed e.g. on an arXiv preprint PDF will have the format

> The X Collaboration: L. Adleman, J. Bond, C. Cho, [...]

where the collaboration name leads, then a colon, then the individual authors divided by commata. In such case, I,Librarian will produce an authors list 

> Collaboration, The X
> Adleman, L.
> Bond, J.
> Cho, C.
> [...]

and hence the first author has the last name "Collaboration" - simply exporting to BibTeX, most bibstyles would turn this into "Collaboration et al.". The same thing happens for some articles where arXiv has the collaboration name stored as an alias to the full author list. In this case, adding a record from the arXiv PDF will produce "Collaboration, The X" as the sole author.

I realize this is a small thing - easily mitigated by paying particular attention when adding records. Just thought to add it to the bug tracker since the colon (instead of comma) used by arXiv in this case, and the keyword "collaboration" (which isn't anybody's actual last name) should make it possible to handle this intuitively from the start.

I hope this report was clear and helpful.

**Comment by mkucej** [comment]
Could you please provide an Arxiv ID with a record having such author list. Thank you.

**Comment by christophra** [comment]
Two examples:

1) http://arxiv.org/pdf/0902.0131v2.pdf
This has both the collaboration name and author list, which seems to be an older style for arXiv (but nevertheless still around, especially since most people don't re-download PDFs.) Importing a new record from this results in the author list "Collaboration, The IceCube; Abbasi, R." (and no further authors, somehow).

2) http://arxiv.org/abs/1109.6096v1
has the author list alias on the page, and the full author list (sans collaboration name) in the PDF. Adding a record from the PDF results in one single author: "Collaboration, The IceCube". The journal doesn't have this alias, so adding the DOI 10.1016/j.astropartphys.2012.01.004 results in the complete author list, instead.

**Comment by mkucej** [comment]
Thank you. I, Librarian imports Arxiv metadata from their search API, not PDFs. These records don't have the full author list:

http://export.arxiv.org/api/query?id_list=1109.6096
```xml
<author>
    <name> The IceCube Collaboration</name>
</author>
```
http://export.arxiv.org/api/query?id_list=0902.0131
```xml
<author>
    <name> IceCube Collaboration</name>
</author>
<author>
    <name>R. Abbasi</name>
</author>
```

So everything is working as intended. You could try to ask Arxiv to always include the full list of authors, but I doubt they will do that. The simplest way is to Update the record from Crossref, after you recorded it.
