### ISSUE TITLE
pdftotext - DOI hyphen removed at line break

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#77]
Hi,

recently I got a PDF which included the DOI breaking at the end of the line using a hyphen. This character actually is part of the DOI but is removed by pdftotext.
pdftohtml -xml would reveal the missing hyphen however the DOI is not complete but broken into an additional tag.

`<text top="1030" left="77" width="360" height="10" font="6">as <i>Blood </i>First Edition paper, February 1, 2011; DOI 10.1182/blood-2010-10-</text>`
`<text top="1043" left="77" width="37" height="10" font="6">311704.</text>
`

Maybe this issue cannot be solved automatically, though.
DOI should read ..2010-10-31...

![image](https://cloud.githubusercontent.com/assets/15378237/16380596/45852ad2-3c78-11e6-8847-4c654ffa88b6.png)

--
--tbf

**Comment by mkucej** [comment]
Unfortunately, there is not much it can be done, if a DOI is split with a new line. Newline is an illegal character for a DOI number. Also, joining lines would create more problems then it would solve.
