### ISSUE TITLE
Author autocomplete in manual upload & edit

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#8]
Hello Martin,
I wrote about this bug in previous tracking system, maybe it was lost.
During manually upload the item if one clicks on "+" button for adding authors and starts to print author name in this new field no quick guess appears. It also happens when editing existing item and doesn't depend on overall author name already present. I assume something wrong with the very text field which is added by "+" button on any stage.

Good luck,
Eugene.

**Comment by mkucej** [comment]
Google tracking system will be closed down next week. I am working on this bug. Thank you for reporting it.

**Comment by mkucej** [comment]
A fix will appear in the next release.

**Comment by Zugrik** [comment]
that is great! thanks a lot.
