### ISSUE TITLE
4.3 xenial console installer issues

### ISSUE THREAD

**Issue by hansduo** [mkucej/i-librarian#80]
I just wanted to upgrade my I,librarian installation on ubuntu xenial (server ed.) from 4.1 to 4.3 via the new xenial console installer.
1. when the installer asked whether the default install location should be used (y/n?) it ignored n as an answer (install.sh: 12: [: n: unexpected operator) and instead just went ahead using the default location. (In case of the apache alias the same problem occured, but this time the default seems to have worked in favour of me. ->see end of this post)
2. the installer then went on to install the prerequisites (that were already fulfilled as it noted). But nevertheless the installation of many new packages was triggered without the possiblity to intervene. All of them in support of libre-office ?

Installing Ghostscript, Poppler-utils, Pdftk and Tesseract OCR:

ghostscript is already the newest version (9.18~dfsg~0-0ubuntu2).
poppler-utils is already the newest version (0.41.0-0ubuntu1).
tesseract-ocr is already the newest version (3.04.01-4).
The following additional packages will be installed:
  acl adwaita-icon-theme at-spi2-core ca-certificates-java colord colord-data dbus-x11 dconf-gsettings-backend
  dconf-service default-jre default-jre-headless dictionaries-common emacsen-common fonts-dejavu fonts-dejavu-extra
  fonts-liberation fonts-opensymbol fonts-sil-gentium fonts-sil-gentium-basic fonts-stix gconf-service
  gconf-service-backend gconf2 gconf2-common glib-networking glib-networking-common glib-networking-services
  gsettings-desktop-schemas gstreamer1.0-plugins-base hicolor-icon-theme humanity-icon-theme hunspell-en-us
  java-common libabw-0.1-1v5 libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libavahi-glib1
  libbonobo2-0 libbonobo2-common libboost-date-time1.58.0 libboost-filesystem1.58.0 libboost-iostreams1.58.0
  libboost-system1.58.0 libcairo-gobject2 libcanberra0 libcdparanoia0 libcdr-0.1-1 libclucene-contribs1v5
  libclucene-core1v5 libcmis-0.5-5v5 libcolamd2.9.1 libcolord2 libcolorhug2 libcroco3 libdconf1 libdrm-amdgpu1
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libe-book-0.1-1 libegl1-mesa libeot0 libepoxy0 libetonyek-0.1-1
  libexif12 libexttextcat-2.0-0 libexttextcat-data libflac8 libfreehand-0.1-1 libgbm1 libgconf-2-4 libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-common libgif7 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglew1.13 libgnome-2-0
  libgnome2-common libgnomevfs2-0 libgnomevfs2-common libgphoto2-6 libgphoto2-l10n libgphoto2-port12
  libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libgudev-1.0-0 libgusb2 libharfbuzz-icu0 libhsqldb1.8.0-java libhunspell-1.3-0 libhyphen0 libice6
  libieee1284-3 libjson-glib-1.0-0 libjson-glib-1.0-common liblangtag-common liblangtag1 libllvm3.8 libltdl7 libmhash2
  libmirclient9 libmircommon5 libmirprotobuf3 libmspub-0.1-1 libmwaw-0.3-3 libmythes-1.2-0 libneon27-gnutls libnspr4
  libnss3 libnss3-nssdb libodfgen-0.1-1 libogg0 libopus0 liborbit-2-0 liborc-0.4-0 liborcus-0.10-0v5
  libpagemaker-0.0-0 libpciaccess0 libpcsclite1 libpolkit-agent-1-0 libpolkit-backend-1-0 libprotobuf-lite9v5
  libproxy1v5 libpulse0 libpython3.5 libraptor2-0 librasqal3 librdf0 libreoffice-avmedia-backend-gstreamer
  libreoffice-base libreoffice-base-core libreoffice-base-drivers libreoffice-calc libreoffice-common libreoffice-core
  libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-java-common libreoffice-math
  libreoffice-pdfimport libreoffice-report-builder-bin libreoffice-sdbc-firebird libreoffice-sdbc-hsqldb
  libreoffice-style-elementary libreoffice-style-galaxy libreoffice-writer librest-0.7-0 librevenge-0.0-0 librsvg2-2
  librsvg2-common libsane libsane-common libservlet3.1-java libsm6 libsndfile1 libsoup-gnome2.4-1 libsoup2.4-1
  libsuitesparseconfig4.4.6 libtheora0 libtxc-dxtn-s2tc0 libvisio-0.1-1 libvisual-0.4-0 libvorbis0a libvorbisenc2
  libvorbisfile3 libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa libwayland-server0 libwpd-0.10-10
  libwpg-0.3-3 libwps-0.4-4 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1
  libxcb-xfixes0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2
  libxshmfence1 libxtst6 libxxf86vm1 libyajl2 lp-solve openjdk-8-jre openjdk-8-jre-headless policykit-1 python3-uno
  sound-theme-freedesktop ubuntu-mono uno-libs3 ure x11-common

Do you want this installer to configure Apache Alias for I, Librarian? [y/n]
n
install.sh: 62: [: n: unexpected operator
-e 
Creating Alias skipped.

**Comment by mkucej** [comment]
Try to execute the installer using `bash` instead of `sh`. Libreoffice is used by I, Librarian to convert office files to PDFs. If you don't need that, you can edit the install script and remove libreoffice from the installation procedure.

**Comment by hansduo** [comment]
...worked, thanks!
