### ISSUE TITLE
links to pubmed entries are dead

### ISSUE THREAD

**Issue by hansduo** [mkucej/i-librarian#82]
This is because the domain pubmed.org is not used anymore -  ncbi.nlm.nih.gov/pubmed should be used instead.

**Comment by mkucej** [comment]
Was there any announcement that they are abandoning the domain? I am going to wait for NCBI to get their act together first.

**Comment by hansduo** [comment]
It has been dead for several weeks now…but I did not read anything official.
Cheers,
Mark

**Comment by mkucej** [comment]
Oh, well. Disappointing how reckless they are . There is going to be another release in August, where I will address this. Thanks for letting me know.

**Comment by hansduo** [comment]
perhaps it is in relation with their switch to https:
http://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/ <http://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/>

**Comment by mkucej** [comment]
Yes, the https is the reason for our new release in August.

**Comment by mkucej** [comment]
Fixed in 4.4

**Comment by hansduo** [comment]
Hi Martin,

just installed 4.5 (which in the about still calls itself 4.4).
Thanks for this update!
Is there a reason why ithe pubmed link has been “degraded” to a mere generic link?

Regards,
Mark

**Comment by hansduo** [comment]
Hi again,

while the test upgrade on ubuntu xenial with only 1 paper in the library worked well,
the upgrade of our trusty ubuntu server with several thousand db-entries seems to have some problems after the upgrade:
After restarting apache when the update was finished it took 5-10 minutes until the webif was accessible again.
I assumed that this had to do something with the change of the pubmed links in the database, but obviously this was not the case, because:
Those dead pubmed links stayed as they were before the update.
Trying to update any paper's meta-info from pubmed (or crossref) throws an error:
call to undefined function() curl_init on line 807 in functions.php.

Regards,
Mark

**Comment by hansduo** [comment]
The reason was that curl could not be found (info from “installation details" in the webif).
installing  php5-curl  resolved the issue.
Maybe this is something that should be fixed in the console installer that I used (the trusty one)?

a) Is the need for curl (called via php) something added in 4.4/4.5? 

b) is there a way to call a migration script in order to fix all the dead pubmed links? Re-running the installer did not help…

Regards,
Mark

**Comment by mkucej** [comment]
>  the update was finished it took 5-10 minutes

This is normal. The PDFs and supplementary files were moved to new folders.

> pubmed link has been “degraded” to a mere generic link

This got unnoticed. Will be fixed later.

> dead pubmed links stayed as they were

Hmm. I thought this was fixed. Will look at it again.

> Is the need for curl (called via php) something added in 4.4/4.5?

Yes. It is required to connect to all Web resources. Curl works well with HTTPS, unlike vanilla PHP. I will fix the installers and readme.

**Comment by mkucej** [comment]
Fixes and workarounds added to 4.6.
