### ISSUE TITLE
Error in functions.php

### ISSUE THREAD

**Issue by Pigno** [mkucej/i-librarian#85]
Hello,

I've updated I, Librarion with v 4.6 and i have an issue with the importation of pdf with DOI.
I'v got the error "call to undefined function curl_init() in C:\I, Librarian\functions.php on line 807.
for every pdf I tried to import with this method.

In the Installation details Menu, i have one line in error :
curl	getting         resources from the Web	         not installed	         !!!

Do you have any idea for helping me ?

Thx a lot !

**Comment by chherr** [comment]
Hi,
I have the same problem after installing v 4.6. I already read the closed posts here, where this is mentioned. I can't get this problem solved. I use Windows 7 and installed over a previous version. I already copied libeay32.dll and ssleay32.dll to php and system32 directories, nothing worked.
Please solve it, I need librarian on a daily basis at work. (Sorry, we have no funding for the hosted version and I like having my library travelling with me).
Thank you.

Best, Christian

**Comment by mkucej** [comment]
Your Windows is probably missing some DLLs. Try to add your path to `I, Librarian Server\php` to the Windows PATH environmental variable and restart. That should enable curl.
