### ISSUE TITLE
help find duplicate 

### ISSUE THREAD

**Issue by pinsardfr** [mkucej/i-librarian#86]
Hey
on https://i-librarian.net/support.phpthe video "detect and remove duplicate records" is 7 years old. Tools/Find duplicate does not exist in  iLibrarian 4.1. Any update ?
Regards
Françoise

**Comment by chherr** [comment]
Hi,
you will find it unter "Tools". The 3rd from the top is "Find Duplicates", at least in iLibrarian 4.6.

Best, Christian
