### ISSUE TITLE
Information display when upgrading

### ISSUE THREAD

**Issue by arwinj** [mkucej/i-librarian#87]
Hi everyone.
When upgrading to the latest version, the first load of the website take some times to process. As I understand it, some upgrading script are used to adapt the library database to the new version.
If the load is aborted, part of the pdf files are missing.

I recommand adding an informative text to the loading page, showing what background process is running, in order for the user to wait before trying to reload manually.

**Comment by mkucej** [comment]
Thank you for the suggestion. The user abort should be ignored, but there is a bug here: https://github.com/mkucej/i-librarian/blob/master/migrate7.php#L7

it should be:
```php
ignore_user_abort(true);
```

**Comment by mkucej** [comment]
Fixed in 4.7
