### ISSUE TITLE
New queries in Miscellaneous menu

### ISSUE THREAD

**Issue by Zugrik** [mkucej/i-librarian#9]
Hello, Martin.

What do you think about this small enhancement: add in "Miscellaneous" menu (left side of Library interface) queries "Items with notes" and "Items with discussions"?

Best,
Eugene.

**Comment by mkucej** [comment]
Good idea. Currently, you can search for all items with notes, if you search with a wild card <?> in advanced search PDF Notes, or Rich-Text Notes tab.

**Comment by Zugrik** [comment]
Thank you very much for the hint! Sure I will use it from now on.

**Comment by mkucej** [comment]
These enhancements will appear in the next release.
