### ISSUE TITLE
PhP. ini modifications

### ISSUE THREAD

**Issue by JMPeryn** [mkucej/i-librarian#91]
Hi,
I just upgraded to IL 4.6. Eveything worked fine but the "Add Multiple pdf" is not working anymore. I was wondering why. (It just start to puload the first (out of 20) pdf then stop)

Looking at the Required php.ini settings: I see that max_input_vars is set at 1000 instead of 10000.  Also, he "file_uploads" is 1 
I tried to modify the php.ini file in the "I librarian Server folder" but the mod I introduce are not translated in the Installation setting. is there something I am missing ? 
Best

JM

**Comment by JMPeryn** [comment]
Actually, 
the curl "getting resources from the Web" also appears as not installed (LDAP authentication neither).
I Uninstalled/reInstalled .. did not solved the pb.

**Comment by mkucej** [comment]
https://github.com/mkucej/i-librarian/issues/85

**Comment by JMPeryn** [comment]
Indeed, this was a #85 issue. Solved. 
Thanks
