### ISSUE TITLE
PDFs from sciencedirect won't download (resolved)

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian#93]
Due to the many redirections the PDFs from sciencedirect won't download. This can be solved by updating the curl options in `functions.php`.

In the function `getFromWeb` the following code needs to be added to the `curl_setopt` block after the setting for `CURLOPT_FOLLOWLOCATION`:

`curl_setopt($curl, CURLOPT_AUTOREFERER, 1);`

After this the redirects work again with curl, enabling the addition of the PDF from a web uri.

**Comment by mkucej** [comment]
Thank you! Fixed in 4.7.
