### ISSUE TITLE
Fatal error in C:\I, Librarian\functions.php on line 807

### ISSUE THREAD

**Issue by ophiuchi** [mkucej/i-librarian#98]
Hi everyone, 

I installed I, Librarian 4.6 (installer with Apache & PHP) and the Visual C++ Redistributable 2012 package. Everything worked fine during Installation. 

The problem is when I want to search in PubMed database (Librarian > Add Record > PubMed) I get the following error:
Fatal error: Call to undefined function curl_init() in C:\I, Librarian\functions.php on line 807

Can someone help me please? 

Thank you!

**Comment by mkucej** [comment]
Look here for solution: #85
